name: owl2anything

on:
  push:
    branches: [suturobocup]
  workflow_dispatch:

env:
  OWL2ANYTHING_VERSION: 1.0.3

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: "17"

      - name: Download owl2anything
        run: |
          curl -L -o owl2anything.zip https://github.com/malte3d/Owl2Anything/releases/download/$OWL2ANYTHING_VERSION/owl2anything-$OWL2ANYTHING_VERSION.zip
          unzip owl2anything.zip

      - name: Run owl2anything
        run: java -jar owl2anything-$OWL2ANYTHING_VERSION/owl2anything-$OWL2ANYTHING_VERSION.jar -i "suturo_knowledge/owl/suturo.owl" -o "SUTURO_Objects.csv" --root "http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#PhysicalObject" --mapping "owl2anything-$OWL2ANYTHING_VERSION/owl2anything/iri_mapping_default.csv" --namespaces "owl2anything-$OWL2ANYTHING_VERSION/owl2anything/iri_namespaces_default.csv"

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: owl2anything-output
          path: |
            owl2anything/output/*
